databases:
  - name: people-wiki-db
    plan: free
    databaseName: peoplewiki

services:
  - type: web
    name: people-wiki
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: people-wiki-db
          property: connectionString
